[locations]
"Azalea PC (Johto)" = ["Azalea Pokecenter", "19", "14"]
"Blackthorn PC (Johto)" = ["Blackthorn Pokecenter", "19", "14"]
"Cerulean PC (Kanto)" = ["Cerulean City Pokecenter", "19", "14"]
"Celadon PC (Kanto)" = ["Celadon City Pokecenter", "19", "14"]
"Cianwood PC (Johto)" = ["Cianwood Pokecenter", "19", "14"]
"Cinnabar PC (Kanto)" = ["Cinnabar Island Pokecenter", "19", "14"]
"Cherrygrove PC (Johto)" = ["Cherrygrove Pokecenter", "19", "14"]
"Dewford PC (Hoenn)" = ["Dewford Pokecenter", "19", "14"]
"Ecruteak PC (Johto)" = ["Ecruteak Pokecenter", "19", "14"]
"Fuchsia PC (Kanto)" = ["Fuchsia City Pokecenter", "19", "14"]
"Goldenrod PC (Johto)" = ["Goldenrod Pokecenter", "19", "14"]
"Mahogany PC (Johto)" = ["Mahogany Pokecenter", "19", "14"]
"Safari PC (Johto)" = ["Johto Safari Zone Pokecenter", "19", "14"]
"Olivine PC (Johto)" = ["Olivine Pokecenter", "19", "14"]
"Pewter PC (Kanto)" = ["Pewter City Pokecenter", "19", "14"]
"Petalburg PC (Hoenn)" = ["Petalburg Pokecenter", "19", "14"]
"Saffron PC (Kanto)" = ["Saffron City Pokecenter", "19", "14"]
"Verdanturf PC (Kanto)" = ["Verdanturf Pokecenter", "19", "14"]
"Vermilion PC (Kanto)" = ["Vermilion City Pokecenter", "19", "14"]
"Viridian PC (Kanto)" = ["Viridian City Pokecenter", "19", "14"]
"Violet PC (Johto)" = ["Violet Pokecenter", "19", "14"]